<?php

return [
    'genres' => [
        ['key' => 'action',      'movie' => 28,    'tv' => 10759, 'label' => 'Action'],
        ['key' => 'adventure',   'movie' => 12,    'tv' => null, 'label' => 'Adventure'],
        ['key' => 'comedy',      'movie' => 35,    'tv' => 35,    'label' => 'Comedy'],
        ['key' => 'drama',       'movie' => 18,    'tv' => 18,    'label' => 'Drama'],
        ['key' => 'scifi',       'movie' => 878,   'tv' => 10765, 'label' => 'Sci-Fi & Fantasy'],
        ['key' => 'horror',      'movie' => 27,    'tv' => 9648,  'label' => 'Horror & Mystery'],
        ['key' => 'thriller',    'movie' => 53,    'tv' => 80,    'label' => 'Thriller & Crime'],
        ['key' => 'romance',     'movie' => 10749, 'tv' => 10749, 'label' => 'Romance'],
        ['key' => 'animation',   'movie' => 16,    'tv' => 16,    'label' => 'Animation'],
        ['key' => 'family',      'movie' => 10751, 'tv' => 10751, 'label' => 'Family'],
        ['key' => 'documentary', 'movie' => 99,    'tv' => 99,    'label' => 'Documentary'],
        ['key' => 'crime',       'movie' => 80,    'tv' => 80,    'label' => 'Crime'],
        ['key' => 'mystery',     'movie' => 9648,  'tv' => 9648,  'label' => 'Mystery'],
        ['key' => 'history',     'movie' => 36,    'tv' => 18,    'label' => 'History'],
        ['key' => 'war',         'movie' => 10752, 'tv' => 10768, 'label' => 'War & Politics'],
        ['key' => 'fantasy',     'movie' => 14,    'tv' => 10765, 'label' => 'Fantasy'],
        ['key' => 'music',       'movie' => 10402, 'tv' => null,  'label' => 'Music'],
        ['key' => 'western',     'movie' => 37,    'tv' => 37,    'label' => 'Western'],
        ['key' => 'tv_movie',    'movie' => 10770, 'tv' => null,  'label' => 'TV Movie'],
        ['key' => 'kids',        'movie' => null,  'tv' => 10762, 'label' => 'Kids'],
        ['key' => 'news',        'movie' => null,  'tv' => 10763, 'label' => 'News'],
        ['key' => 'reality',     'movie' => null,  'tv' => 10764, 'label' => 'Reality'],
        ['key' => 'soap',        'movie' => null,  'tv' => 10766, 'label' => 'Soap'],
        ['key' => 'talk',        'movie' => null,  'tv' => 10767, 'label' => 'Talk'],
    ],
];
